version: '3.3'
services:
  db:
    container_name: foodgram-db
    image: postgres:15.2-alpine
    restart: always
    # ports:
    #   - 32700:5432
    env_file:
      - ./.env
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    container_name: foodgram-backend
    image: mrvilbi/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram-frontend
    image: mrvilbi/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - docs:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

networks:
  enrollment:
    driver: bridge

volumes:
  static_value:
  media_value:
  db_value:
  docs:
